### ISSUE TITLE
Library not being correctly imported

### ISSUE THREAD

**Issue by benzgrant** [twitchtv/igdb-api-python#6] opened 2020-11-13 19:46 UTC
Hello,
I have a problem with this library. I am following the example in the README file, in particular the section called "Using your Twitch Credentials".

When I try to run the script, I get the following error:
ModuleNotFoundError: No module named 'igdb.wrapper'; 'igdb' is not a package

❯ python -V
Python 3.9.0

**Comment by ReenigneArcher** [comment] 2021-02-06 00:17
You need to install the module or put the igdb module folder in the same folder as your python script.

**Comment by felixnorden** [comment] 2021-03-19 12:37
Thanks @ReenigneArcher for giving this pointer!

Sorry for the late reply @benzgrant, have things been resolved for you, or would you still like some help? :)

**Comment by dustyjewett** [comment] 2021-03-29 10:55
Closing on the assumption that the problem is resolved. Please re-open if you need more help.

**Closed by dustyjewett** 2021-03-29 10:55 UTC

**Comment by azuravian** [comment] 2022-05-07 19:01
I was getting this same error and found what the problem might be if others are experiencing this.  Do not name any of your .py files igdb.py.  This causes a circular import.
